query getCoursesDashboard {
    getCoursesDashboard {
        id
        name
        description
    }
}

query getCourseDashboard($getCourseId: Int!) {
    getCourseDashboard(id: $getCourseId) {
        id
        name
        description
        lectures {
            id
            name
            description
            video
            order
        }
    }

}


