query GetUsersByPatient {
  UsersByPatient {
    id
    name
    lastname
    roles
    specialties
    active
    high_date
    speicalty
    degree
    avatar
    facebook
    instragram
    info_visible
  }
}

query GetPatientMessageById($patient_id: Int) {
  getPatientMessageById(patient_id: $patient_id) {
    from_id
    from_type
    from_name
    from_email
    to_id
    to_type
    to_name
    to_email
    subject
    content
    attachment
    create_date
    request_id
    notification
  }
}

query GetUserForMessage {
  getUserForMessage {
    id
    name
    lastname
    email
  }
}
