query GetNutritionsForDashboard($patient_id: Int) {
  getNutritionsForDashboard(patient_id: $patient_id) {
    name
    detail
    start_date
    end_date
    document
  }
}

query GetNutritionPurchaseStatus($patient_id: Int) {
  getNutritionPurchaseStatus(patient_id: $patient_id)
}
