query GetOnlinePlanByDashboard($patient_id: Int, $select_date: Date) {
  getOnlinePlanByDashboard(patient_id: $patient_id, select_date: $select_date)
}

query GetVideoLinkById($video_id: Int) {
  getVideoLinkById(video_id: $video_id)
}

query GetVideoMaterial($video_id: Int) {
  getVideoMaterial(video_id: $video_id) {
    id
    name
    details
  }
}

query GetAvailablePlanDates($patient_id: Int) {
  getAvailablePlanDates(patient_id: $patient_id)
}

query GetAvailablePlanDates($patient_id: Int) {
  getAvailablePlanDates(patient_id: $patient_id)
}
