query GetServicePurchaseByDashboard($patient_id: Int, $year: Int) {
  getServicePurchaseByDashboard(patient_id: $patient_id, year: $year)
}

query GetPurchasesFromBillNumber($bill_number: Int) {
  getPurchasesFromBillNumber(bill_number: $bill_number)
}

query GetSessionsByIdFromDashboard($patient_id: Int, $purchase_id: Int) {
  getSessionsByIdFromDashboard(patient_id: $patient_id, purchase_id: $purchase_id) {
    id
    date
    status
    session_count
    user {
      id
      name
      lastname
      specialties
    }
  }
}

query GetPurchasedOnlinePlanList($patient_id: Int) {
  getPurchasedOnlinePlanList(patient_id: $patient_id) {
    id
    item_name
  }
}

mutation CancelOnlinePlanSubscriptionByDashboard($purchase_id: Int) {
  CancelOnlinePlanSubscriptionByDashboard(purchase_id: $purchase_id)
}
