query GetSessionsByDashboard($patient_id: Int) {
  getSessionsByDashboard(patient_id: $patient_id) {
    id
    start_time
    end_time
    location {
      name
      color
    }
    purchase {
      item_web_name
    }
    stream_event
  }
}

query GetLocationByDashboard {
  getSessionsByDashboard {
    id
    name
    color
  }
}
