query GetClasslandMain {
  getClasslandMain {
    id
    title
    text
    url
    images
  }
}

query GetClasslandCategory($category: String) {
  getClasslandCategory(category: $category) {
    id
    image
    name
    description
    url
    price
    difficulty
    category
    visible
    order
  }
}

query GetClasslandFaqs {
  getClasslandFaqs {
    id
    name
    description
    visible
    order
  }
}
