query GetClasslands($category: String) {
  getClasslands(category: $category) {
    id
    image
    name
    description
    url
    price
    difficulty
    category
    visible
  }
}

query GetFaqs {
  getFaqs {
    id
    name
    description
    visible
  }
}
