query GetUser {
  getUser {
    id
    email
    name
  }
}

mutation CreateUser {
  createUser {
    id
  }
}

# contact page
query GetContactInfo {
  getContactInfo {
    id
    phone_one
    phone_two
    email_one
    email_two
  }
}
