query GetPurchaseListByDashboard($patient_id: Int) {
  getPurchaseListByDashboard(patient_id: $patient_id)
}

query GetWeekDaySessionsByDashboard($patient_id: Int) {
  getWeekDaySessionsByDashboard(patient_id: $patient_id)
}

query GetPaymentStatusForDashboard($patient_id: Int) {
  getPaymentStatusForDashboard(patient_id: $patient_id) {
    summary_type,
    values,
  }
}

query GetPendingQuestionnaireByDashboard {
  getPendingQuestionnaireByDashboard {
    id
    name
    specialties
    questionnaire
  }
}

mutation UpdateCompletedQuestionnaireByDashboard($id: Int!, $attachment: [Upload], $questionnaire: JSON!) {
  updateCompletedQuestionnaireByDashboard(id: $id, attachment: $attachment, questionnaire: $questionnaire) {
    id
    name
    specialties
    questionnaire
  }
}
