query GetFemHealth {
  getFemHealth {
    id
    title_one
    title_two
    sub_title
    text
    images
    list
  }
}

query GetDisciplineList {
  getDisciplineList {
    id
    name
    order
    image
  }
}

query GetFemHealthService($discipline_id: Int) {
  getFemHealthService(discipline_id: $discipline_id) {
    id
    name
    title_one
    title_two
    text
    discipline_id
    carousel_image
    stream_button
    personal_button
    online_button
  }
}
