query GetFemHealth {
  getFemHealth {
    id
    title_one
    title_two
    sub_title
    text
    images
    list
  }
}

query GetDisciplineList {
  getDisciplineList {
    id
    name
    order
    image
    stream_button
    online_button
    personal_button
  }
}

query GetFemHealthService($discipline_id: Int) {
  getFemHealthService(discipline_id: $discipline_id) {
    id
    name
    title_one
    title_two
    text
    discipline_id
    carousel_image
    stream_button
    personal_button
    online_button
  }
}

query GetFemHealthServiceSubjectByType($discipline_id: Int, $service_type: String) {
  getFemHealthServiceSubjectByType(discipline_id: $discipline_id, service_type: $service_type) {
    bono_text
    services
  }
}
