query GetMainImage {
  getMainImage {
    id
    path
    text_one
    text_two
  }
}

query GetFeaturedServices {
  getFeaturedServices {
    id
    subject
    image
    title
    detail
    url
    text
    active
  }
}

query GetEquipo {
  getEquipo {
    id
    title
    description
    images
    avatar
    text_one
    text_two
    sign
    facebook
    instagram
  }
}
