query GetNewsListForDashboard {
  getNewsListForDashboard {
    id
    category_id
    publish_date
    title
    description
    images
    content
  }
}

query GetNewsByIdForDashboard($id: Int) {
  getNewsByIdForDashboard(id: $id) {
    id
    category_id
    publish_date
    title
    description
    images
    content
  }
}

query GetNewsListWithCategory($category_id: Int) {
  getNewsListWithCategory(category_id: $category_id) {
    id
    category_id
    publish_date
    title
    description
    images
    content
  }
}
