query GetNewsListForDashboard {
  getNewsListForDashboard {
    id
    category_id
    publish_date
    title
    description
    images
  }
}

query GetNewsByIdForDashboard($id: Int) {
  getNewsByIdForDashboard(id: $id) {
    id
    category_id
    publish_date
    title
    description
    images
  }
}
