query GetPatientByEmail($email: String) {
  getPatientByEmail(email: $email)
}

query GetAnthropmetryByDashboard($patient_id: Int) {
  getAnthropmetryByDashboard(patient_id: $patient_id)
}

query GetAnthroDetailDataByDashboard($patient_id: Int) {
  getAnthroDetailDataByDashboard(patient_id: $patient_id)
}

mutation UpdatePatientByDashboard(
  $email: String
  $name: String
  $lastname: String
  $dni: String
  $mobile: String
  $eg_number: String
  $known_us: String
  $avatar: Upload
  $genre: String
  $birth_date: Date
  $bill_alias: String
  $bill_name: String
  $bill_address: String
  $bill_province: String
  $bill_town: String
  $bill_postal_code: String
  $bill_country: String
) {
  updatePatientByDashboard(
    email: $email
    name: $name
    lastname: $lastname
    dni: $dni
    mobile: $mobile
    eg_number: $eg_number
    known_us: $known_us
    avatar: $avatar
    genre: $genre
    birth_date: $birth_date
    bill_alias: $bill_alias
    bill_name: $bill_name
    bill_address: $bill_address
    bill_province: $bill_province
    bill_town: $bill_town
    bill_postal_code: $bill_postal_code
    bill_country: $bill_country
  ) {
    id
  }
}

mutation UpdateAnthropometry(
  $patient_id: Int
  $grasa: String
  $visceral: String
  $osea: String
  $imc: String
  $agua: String
  $muscular: String
  $basal: String
  $edad: String
  $peso: String
  $altura: String
  $cintura: String
  $brazo: String
  $cadera: String
  $muslo: String
) {
  updateAnthropometry(
    patient_id: $patient_id
    grasa: $grasa
    visceral: $visceral
    osea: $osea
    imc: $imc
    agua: $agua
    muscular: $muscular
    basal: $basal
    edad: $edad
    peso: $peso
    altura: $altura
    cintura: $cintura
    brazo: $brazo
    cadera: $cadera
    muslo: $muslo
  )
}

mutation DeletePatientByDashboard($patient_id: Int!) {
  deletePatientByDashboard(patient_id: $patient_id) {
    id
  }
}
