mutation Checkout($serviceId: Int, $ccToken: String, $paymentType: String, $isGift: Boolean) {
  Checkout(service_id: $serviceId, cc_token: $ccToken, payment_type: $paymentType, is_gift: $isGift) {
    id
    patient_id
    item_kind
    item_id
    item_name
    item_web_name
    item_speciality
    item_count
    item_iva
    item_sessions
    item_used
    status
    purchase_date
    purchase_type
    bill_number
    price
    gross_amount
    discount
    amount
    stripe_payment_intent_id
    stripe_subscription_id
    next
  }
}

query CheckoutVerify($intentId: String, $subscriptionId: String, $purchaseId: String) {
  checkoutVerify(intent_id: $intentId, subscription_id: $subscriptionId, purchase_id: $purchaseId) {
    item_web_name
    status
    id
    patient_id
    item_kind
    item_name
    item_id
    item_speciality
    item_count
    item_iva
    item_sessions
    item_used
    purchase_date
    purchase_type
    bill_number
    price
    gross_amount
    discount
    amount
  }
}
