mutation Checkout($serviceId: Int, $ccToken: String) {
  Checkout(service_id: $serviceId, cc_token: $ccToken) {
    id
    patient_id
    item_kind
    item_id
    item_name
    item_web_name
    item_speciality
    item_count
    item_iva
    item_sessions
    item_used
    status
    purchase_date
    purchase_type
    bill_number
    price
    gross_amount
    discount
    amount
    next
  }
}

query CheckoutVerify($intentId: String) {
  checkoutVerify(intent_id: $intentId) {
    item_web_name
    status
    id
    patient_id
    item_kind
    item_name
    item_id
    item_speciality
    item_count
    item_iva
    item_sessions
    item_used
    purchase_date
    purchase_type
    bill_number
    price
    gross_amount
    discount
    amount
  }
}
