query GetCmsService {
  getCmsService {
    id
    title_one
    text
  }
}

query GetCmsServiceDisciplineList {
  getCmsServiceDisciplineList {
    id
    name
    order
    image
  }
}

query GetCmsServiceSubject($discipline_id: Int) {
  getCmsServiceSubject(discipline_id: $discipline_id) {
    id
    text
    title_two
    images
    personal_image
    online_image
    stream_image
  }
}
