query GetCmsService {
  getCmsService {
    id
    title_one
    text
  }
}

query GetCmsServiceDisciplineList {
  getCmsServiceDisciplineList {
    id
    name
    order
    image
  }
}

query GetCmsServiceSubject($discipline_id: Int) {
  getCmsServiceSubject(discipline_id: $discipline_id) {
    id
    text
    title_two
    carousel_image
    personal_image
    online_image
    stream_image
    stream_button
    personal_button
    online_button
  }
}

query GetCmsServiceSubjectByType($discipline_id: Int, $service_type: [JSON]) {
  getCmsServiceSubjectByType(discipline_id: $discipline_id, service_type: $service_type) {
    bono_text
    services
  }
}
