query GetCmsService {
  getCmsService {
    id
    title_one
    title_two
    sub_title
    text
    images
  }
}

query GetCmsServiceDisciplineList {
  getCmsServiceDisciplineList {
    id
    name
    order
    image
  }
}
