mutation SendCV(
  $email: String!
  $firstName: String!
  $lastName: String!
  $body: String!
  $phone: String!
  $attachment: Upload
  $job_id: Int
) {
  sendCV(
    email: $email
    firstName: $firstName
    lastName: $lastName
    body: $body
    phone: $phone
    attachment: $attachment
    job_id: $job_id
  )
}

query GetJobListForDashboard {
  getJobListForDashboard {
    id
    publish_date
    time
    title
    description
    content
  }
}

query GetJobByIdForDashboard($id: Int) {
  getJobByIdForDashboard(id: $id) {
    id
    publish_date
    time
    title
    description
    content
  }
}
